# Starter pipeline comment
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    clean: true
  - task: Bash@3
    displayName: Sync with Adobe Repo
    condition: eq(variables['Build.SourceBranch'],'refs/heads/main')
    inputs:
     targetType: 'inline'
     script: |
      git remote add adobe https://$(gituser-id):$(gitpassword)@git.cloudmanager.adobe.com/sapientpartnersandbox/Task/
      git pull 
      git push adobe HEAD:main   
  # new code for rest API   
  - task: InvokeRESTAPI@1
    inputs:
      connectionType: 'connectedServiceName'
      serviceConnection: 'genserv'
      method: 'GET'
      urlSuffix: 'https://cloudmanager.adobe.io/api/program/76602 /pipeline/11168759'
      waitForCompletion: 'false'

