# Starter pipeline comment
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    clean: true
  - task: Bash@3
    displpayName: Sync with Adobe Repo
    condition: eq(variables['Build.SourceBranch'],'refs/heads/main')
    inputs:
     targetType: 'inline'
     - script: |
        echo Hello, world!
       displayName: 'Run a one-line script'

     - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml

       displayName: 'Run a multi-line script'

     - script: |
        git remote add adobe https://$(gituser-id):$(gitpassword)@git.cloudmanager.adobe.com/sapientpartnersandbox/Task/
        git pull 
        git push adobe main
      
    

